language: swift

osx_image: 
- xcode10.2
- xcode11

env:
- SCHEME=Kingfisher SWIFT_VERSION=5.0
- SCHEME=Kingfisher-macOS SWIFT_VERSION=5.0
- SCHEME=Kingfisher-tvOS SWIFT_VERSION=5.0
- SCHEME=Kingfisher SWIFT_VERSION=4.2
- SCHEME=Kingfisher-macOS SWIFT_VERSION=4.2
- SCHEME=Kingfisher-tvOS SWIFT_VERSION=4.2
- SCHEME=Kingfisher SWIFT_VERSION=4.0
- SCHEME=Kingfisher-macOS SWIFT_VERSION=4.0
- SCHEME=Kingfisher-tvOS SWIFT_VERSION=4.0

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle exec fastlane test_ci
